--- #YAML:1.0
name:               Media-Type-Simple
version:            0.02
abstract:           MIME Media Types and their file extensions
author:
    - Robert Rothenberg <rrwo@cpan.org>
license:            perl
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
requires:
    Carp:           0
    Storable:       0
    Sub::Exporter:  0
    Test::More:     0
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.48
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
